services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kozmaoliver\SymfonyEventMap\EventScanner:
        arguments:
            $scanDirectories: '%event_map.scan_directories%'
            $excludePatterns: '%event_map.exclude_patterns%'

    Kozmaoliver\SymfonyEventMap\ListenerMapper:
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $container: '@service_container'

    Kozmaoliver\SymfonyEventMap\EventMapService: ~

    Kozmaoliver\SymfonyEventMap\Command\GenerateEventMapCommand:
        tags:
            - { name: console.command }
